-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    dob TEXT,
    gender TEXT,
    uid TEXT UNIQUE NOT NULL,
    phone TEXT,
    blood_group TEXT,
    address TEXT,
    birthmark TEXT,
    dnr BOOLEAN DEFAULT true,
    organ_donor BOOLEAN DEFAULT true,
    local_save BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Medications Table
CREATE TABLE IF NOT EXISTS public.medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    dose TEXT,
    frequency TEXT,
    doctor TEXT,
    hospital TEXT,
    since TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Diseases Table
CREATE TABLE IF NOT EXISTS public.diseases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    since TEXT,
    status TEXT DEFAULT 'active', -- 'active' or 'resolved'
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Surgeries Table
CREATE TABLE IF NOT EXISTS public.surgeries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    date TEXT,
    type TEXT,
    hospital TEXT,
    doctor TEXT,
    city TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    date TEXT,
    lab TEXT,
    type TEXT,
    size TEXT,
    verified BOOLEAN DEFAULT false,
    abnormalities TEXT,
    suggestions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Emergency Contacts Table
CREATE TABLE IF NOT EXISTS public.emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    relation TEXT,
    phone TEXT,
    "primary" BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Consents Table
CREATE TABLE IF NOT EXISTS public.consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    accessor_id TEXT NOT NULL, -- Doctor Licence ID or Hospital ID
    accessor_name TEXT NOT NULL,
    access_type TEXT NOT NULL DEFAULT 'Read', -- 'Read' or 'Write'
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Access Logs Table (Audit Trail)
CREATE TABLE IF NOT EXISTS public.access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    accessor_name TEXT NOT NULL,
    accessor_role TEXT NOT NULL, -- 'doctor' or 'hospital'
    action_type TEXT NOT NULL, -- 'Read', 'Write', 'Emergency Bypass'
    emergency_bypass BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Create Admissions Table (Hospital Portal)
CREATE TABLE IF NOT EXISTS public.admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    patient_name TEXT NOT NULL,
    uid TEXT NOT NULL,
    ward TEXT,
    bed TEXT,
    status TEXT DEFAULT 'Admitted', -- 'Admitted', 'Observation', 'Discharged'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Create Blood Inventory Table (Hospital Portal)
CREATE TABLE IF NOT EXISTS public.blood_inventory (
    "group" TEXT PRIMARY KEY,
    units INTEGER DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Create Staff Shift Table (Hospital Portal)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT DEFAULT 'On Duty', -- 'On Duty', 'On Call', 'Off Duty'
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Create Insurance Table (Hospital Portal / Citizen Portal)
CREATE TABLE IF NOT EXISTS public.insurance (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    ayushman_active BOOLEAN DEFAULT true,
    ayushman_card_no TEXT,
    ayushman_cover TEXT,
    ayushman_expiry TEXT,
    private_active BOOLEAN DEFAULT true,
    private_provider TEXT,
    private_policy_no TEXT,
    private_cover TEXT,
    private_expiry TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ── SEED INITIAL DEMO PATIENT DATA ───────────────────────────────────────────

-- Seed Profile for Rahul Sharma
INSERT INTO public.profiles (id, name, dob, gender, uid, phone, blood_group, address, birthmark, dnr, organ_donor, local_save)
VALUES (
    '78234401-0000-0000-0000-000000000000',
    'Rahul Sharma',
    '14 Aug 1982',
    'Male',
    '7823-XXXX-4401',
    '+91 98100 XXXXX',
    'B+',
    'Block 4B, Janakpuri, New Delhi',
    'Left shoulder, oval ~2cm',
    true,
    true,
    true
) ON CONFLICT (uid) DO UPDATE SET 
    name = EXCLUDED.name, 
    dob = EXCLUDED.dob, 
    gender = EXCLUDED.gender, 
    phone = EXCLUDED.phone, 
    blood_group = EXCLUDED.blood_group, 
    address = EXCLUDED.address, 
    birthmark = EXCLUDED.birthmark, 
    dnr = EXCLUDED.dnr, 
    organ_donor = EXCLUDED.organ_donor, 
    local_save = EXCLUDED.local_save;

-- Seed Medications for Rahul Sharma
INSERT INTO public.medications (profile_id, name, dose, frequency, doctor, hospital, since)
SELECT '78234401-0000-0000-0000-000000000000', 'Metformin', '500mg', 'Twice daily', 'Dr. S. Kapoor', 'AIIMS', 'Jan 2020'
WHERE NOT EXISTS (SELECT 1 FROM public.medications WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Metformin');

INSERT INTO public.medications (profile_id, name, dose, frequency, doctor, hospital, since)
SELECT '78234401-0000-0000-0000-000000000000', 'Amlodipine', '5mg', 'Once daily', 'Dr. R. Mehta', 'City Hospital', 'Mar 2022'
WHERE NOT EXISTS (SELECT 1 FROM public.medications WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Amlodipine');

INSERT INTO public.medications (profile_id, name, dose, frequency, doctor, hospital, since)
SELECT '78234401-0000-0000-0000-000000000000', 'Atorvastatin', '20mg', 'Nightly', 'Dr. S. Kapoor', 'AIIMS', 'Jun 2022'
WHERE NOT EXISTS (SELECT 1 FROM public.medications WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Atorvastatin');

INSERT INTO public.medications (profile_id, name, dose, frequency, doctor, hospital, since)
SELECT '78234401-0000-0000-0000-000000000000', 'Pantoprazole', '40mg', 'Morning', 'Dr. N. Gupta', 'Apollo', 'Feb 2023'
WHERE NOT EXISTS (SELECT 1 FROM public.medications WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Pantoprazole');

-- Seed Diseases for Rahul Sharma
INSERT INTO public.diseases (profile_id, name, since, status, note)
SELECT '78234401-0000-0000-0000-000000000000', 'Type 2 Diabetes Mellitus', '2019', 'active', 'HbA1c: 7.1% (May 2026)'
WHERE NOT EXISTS (SELECT 1 FROM public.diseases WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Type 2 Diabetes Mellitus');

INSERT INTO public.diseases (profile_id, name, since, status, note)
SELECT '78234401-0000-0000-0000-000000000000', 'Hypertension Stage 1', '2021', 'active', 'BP: 138/88 (Jun 2026)'
WHERE NOT EXISTS (SELECT 1 FROM public.diseases WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Hypertension Stage 1');

INSERT INTO public.diseases (profile_id, name, since, status, note)
SELECT '78234401-0000-0000-0000-000000000000', 'Appendicitis', '2017', 'resolved', 'Resolved via surgery'
WHERE NOT EXISTS (SELECT 1 FROM public.diseases WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Appendicitis');

INSERT INTO public.diseases (profile_id, name, since, status, note)
SELECT '78234401-0000-0000-0000-000000000000', 'Malaria (P. vivax)', '2014', 'resolved', 'Fully recovered'
WHERE NOT EXISTS (SELECT 1 FROM public.diseases WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Malaria (P. vivax)');

INSERT INTO public.diseases (profile_id, name, since, status, note)
SELECT '78234401-0000-0000-0000-000000000000', 'Acute Bronchitis', '2011', 'resolved', 'Resolved with antibiotics'
WHERE NOT EXISTS (SELECT 1 FROM public.diseases WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Acute Bronchitis');

-- Seed Surgeries for Rahul Sharma
INSERT INTO public.surgeries (profile_id, name, date, type, hospital, doctor, city)
SELECT '78234401-0000-0000-0000-000000000000', 'Appendectomy', 'Feb 2017', 'Laparoscopic', 'AIIMS New Delhi', 'Dr. Priya Rao', 'New Delhi'
WHERE NOT EXISTS (SELECT 1 FROM public.surgeries WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Appendectomy');

INSERT INTO public.surgeries (profile_id, name, date, type, hospital, doctor, city)
SELECT '78234401-0000-0000-0000-000000000000', 'Knee Arthroscopy (L)', 'Nov 2020', 'Sports injury', 'Fortis Gurgaon', 'Dr. Anand Joshi', 'Gurgaon'
WHERE NOT EXISTS (SELECT 1 FROM public.surgeries WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Knee Arthroscopy (L)');

INSERT INTO public.surgeries (profile_id, name, date, type, hospital, doctor, city)
SELECT '78234401-0000-0000-0000-000000000000', 'Cataract Extraction (R)', 'Mar 2024', 'Phacoemulsification', 'Sankara Nethralaya', 'Dr. Leena Iyer', 'Chennai'
WHERE NOT EXISTS (SELECT 1 FROM public.surgeries WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Cataract Extraction (R)');

-- Seed Reports for Rahul Sharma
INSERT INTO public.reports (profile_id, name, date, lab, type, size, verified)
SELECT '78234401-0000-0000-0000-000000000000', 'Blood test — HbA1c, Lipid panel', 'May 2026', 'Thyrocare', 'PDF', '1.2 MB', true
WHERE NOT EXISTS (SELECT 1 FROM public.reports WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Blood test — HbA1c, Lipid panel');

INSERT INTO public.reports (profile_id, name, date, lab, type, size, verified)
SELECT '78234401-0000-0000-0000-000000000000', 'MRI right knee', 'Nov 2020', 'Fortis Imaging', 'DICOM', '34 MB', true
WHERE NOT EXISTS (SELECT 1 FROM public.reports WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'MRI right knee');

INSERT INTO public.reports (profile_id, name, date, lab, type, size, verified)
SELECT '78234401-0000-0000-0000-000000000000', 'Discharge summary — Appendectomy', 'Feb 2017', 'AIIMS', 'PDF', '890 KB', true
WHERE NOT EXISTS (SELECT 1 FROM public.reports WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Discharge summary — Appendectomy');

INSERT INTO public.reports (profile_id, name, date, lab, type, size, verified)
SELECT '78234401-0000-0000-0000-000000000000', 'Eye pressure & OCT scan', 'Mar 2024', 'Sankara', 'PDF', '2.1 MB', true
WHERE NOT EXISTS (SELECT 1 FROM public.reports WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Eye pressure & OCT scan');

INSERT INTO public.reports (profile_id, name, date, lab, type, size, verified)
SELECT '78234401-0000-0000-0000-000000000000', 'Chest X-ray', 'Jan 2025', 'Medanta', 'JPG', '4.3 MB', false
WHERE NOT EXISTS (SELECT 1 FROM public.reports WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Chest X-ray');

-- Seed Emergency Contacts for Rahul Sharma
INSERT INTO public.emergency_contacts (profile_id, name, relation, phone, "primary")
SELECT '78234401-0000-0000-0000-000000000000', 'Priya Sharma', 'Spouse', '+91 98100 XXXXX', true
WHERE NOT EXISTS (SELECT 1 FROM public.emergency_contacts WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Priya Sharma');

INSERT INTO public.emergency_contacts (profile_id, name, relation, phone, "primary")
SELECT '78234401-0000-0000-0000-000000000000', 'Rajesh Sharma', 'Brother', '+91 99990 XXXXX', false
WHERE NOT EXISTS (SELECT 1 FROM public.emergency_contacts WHERE profile_id = '78234401-0000-0000-0000-000000000000' AND name = 'Rajesh Sharma');

-- Seed Blood Inventory Initial Values
INSERT INTO public.blood_inventory ("group", units) VALUES
('A+', 24), ('A-', 8), ('B+', 42), ('B-', 12),
('AB+', 15), ('AB-', 4), ('O+', 38), ('O-', 18)
ON CONFLICT ("group") DO UPDATE SET units = EXCLUDED.units;

-- Seed Staff Shifts
INSERT INTO public.staff (name, role, status) VALUES
('Dr. Amit Goel', 'Chief Cardiologist', 'On Duty'),
('Dr. Priya Sen', 'ER Physician', 'On Duty'),
('Dr. Rohan Mehra', 'General Surgeon', 'On Call'),
('Nurse Anjali Sharma', 'ICU Head Nurse', 'On Duty')
ON CONFLICT (id) DO NOTHING;

-- Seed Insurance for Rahul Sharma
INSERT INTO public.insurance (
    profile_id, 
    ayushman_active, 
    ayushman_card_no, 
    ayushman_cover, 
    ayushman_expiry, 
    private_active, 
    private_provider, 
    private_policy_no, 
    private_cover, 
    private_expiry
) 
SELECT 
    '78234401-0000-0000-0000-000000000000',
    true,
    'AB-MP-2203XXXXX',
    '₹5,00,000',
    'Lifetime',
    true,
    'Star Health Insurance',
    'SHI-2024-XXXXX',
    '₹10,00,000',
    'Mar 2027'
WHERE NOT EXISTS (SELECT 1 FROM public.insurance WHERE profile_id = '78234401-0000-0000-0000-000000000000');

-- Disable Row Level Security (RLS) for demo/dev purposes
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.diseases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.surgeries DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.consents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blood_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.insurance DISABLE ROW LEVEL SECURITY;

-- ── DATABASE MIGRATION FOR EXISTING INSTANCES ────────────────────────────────
-- Run these statements in your Supabase SQL Editor if your tables are already created:
-- ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS abnormalities TEXT;
-- ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS suggestions TEXT;
